# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.21.3_1/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.21.3_1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/chris/Desktop/CMU/Research/git/Learning-to-Link

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/chris/Desktop/CMU/Research/git/Learning-to-Link

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.21.3_1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.21.3_1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/chris/Desktop/CMU/Research/git/Learning-to-Link/CMakeFiles /Users/chris/Desktop/CMU/Research/git/Learning-to-Link//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/chris/Desktop/CMU/Research/git/Learning-to-Link/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named DistanceLearning

# Build rule for target.
DistanceLearning: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DistanceLearning
.PHONY : DistanceLearning

# fast build rule for target.
DistanceLearning/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DistanceLearning.dir/build.make CMakeFiles/DistanceLearning.dir/build
.PHONY : DistanceLearning/fast

#=============================================================================
# Target rules for targets named AlphaLinkage

# Build rule for target.
AlphaLinkage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AlphaLinkage
.PHONY : AlphaLinkage

# fast build rule for target.
AlphaLinkage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaLinkage.dir/build.make CMakeFiles/AlphaLinkage.dir/build
.PHONY : AlphaLinkage/fast

distance_main.o: distance_main.cpp.o
.PHONY : distance_main.o

# target to build an object file
distance_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DistanceLearning.dir/build.make CMakeFiles/DistanceLearning.dir/distance_main.cpp.o
.PHONY : distance_main.cpp.o

distance_main.i: distance_main.cpp.i
.PHONY : distance_main.i

# target to preprocess a source file
distance_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DistanceLearning.dir/build.make CMakeFiles/DistanceLearning.dir/distance_main.cpp.i
.PHONY : distance_main.cpp.i

distance_main.s: distance_main.cpp.s
.PHONY : distance_main.s

# target to generate assembly for a file
distance_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DistanceLearning.dir/build.make CMakeFiles/DistanceLearning.dir/distance_main.cpp.s
.PHONY : distance_main.cpp.s

lib/AffineFunction.o: lib/AffineFunction.cpp.o
.PHONY : lib/AffineFunction.o

# target to build an object file
lib/AffineFunction.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaLinkage.dir/build.make CMakeFiles/AlphaLinkage.dir/lib/AffineFunction.cpp.o
.PHONY : lib/AffineFunction.cpp.o

lib/AffineFunction.i: lib/AffineFunction.cpp.i
.PHONY : lib/AffineFunction.i

# target to preprocess a source file
lib/AffineFunction.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaLinkage.dir/build.make CMakeFiles/AlphaLinkage.dir/lib/AffineFunction.cpp.i
.PHONY : lib/AffineFunction.cpp.i

lib/AffineFunction.s: lib/AffineFunction.cpp.s
.PHONY : lib/AffineFunction.s

# target to generate assembly for a file
lib/AffineFunction.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaLinkage.dir/build.make CMakeFiles/AlphaLinkage.dir/lib/AffineFunction.cpp.s
.PHONY : lib/AffineFunction.cpp.s

lib/Clarkson.o: lib/Clarkson.cpp.o
.PHONY : lib/Clarkson.o

# target to build an object file
lib/Clarkson.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaLinkage.dir/build.make CMakeFiles/AlphaLinkage.dir/lib/Clarkson.cpp.o
.PHONY : lib/Clarkson.cpp.o

lib/Clarkson.i: lib/Clarkson.cpp.i
.PHONY : lib/Clarkson.i

# target to preprocess a source file
lib/Clarkson.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaLinkage.dir/build.make CMakeFiles/AlphaLinkage.dir/lib/Clarkson.cpp.i
.PHONY : lib/Clarkson.cpp.i

lib/Clarkson.s: lib/Clarkson.cpp.s
.PHONY : lib/Clarkson.s

# target to generate assembly for a file
lib/Clarkson.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaLinkage.dir/build.make CMakeFiles/AlphaLinkage.dir/lib/Clarkson.cpp.s
.PHONY : lib/Clarkson.cpp.s

lib/Hungarian.o: lib/Hungarian.cpp.o
.PHONY : lib/Hungarian.o

# target to build an object file
lib/Hungarian.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DistanceLearning.dir/build.make CMakeFiles/DistanceLearning.dir/lib/Hungarian.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaLinkage.dir/build.make CMakeFiles/AlphaLinkage.dir/lib/Hungarian.cpp.o
.PHONY : lib/Hungarian.cpp.o

lib/Hungarian.i: lib/Hungarian.cpp.i
.PHONY : lib/Hungarian.i

# target to preprocess a source file
lib/Hungarian.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DistanceLearning.dir/build.make CMakeFiles/DistanceLearning.dir/lib/Hungarian.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaLinkage.dir/build.make CMakeFiles/AlphaLinkage.dir/lib/Hungarian.cpp.i
.PHONY : lib/Hungarian.cpp.i

lib/Hungarian.s: lib/Hungarian.cpp.s
.PHONY : lib/Hungarian.s

# target to generate assembly for a file
lib/Hungarian.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DistanceLearning.dir/build.make CMakeFiles/DistanceLearning.dir/lib/Hungarian.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaLinkage.dir/build.make CMakeFiles/AlphaLinkage.dir/lib/Hungarian.cpp.s
.PHONY : lib/Hungarian.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaLinkage.dir/build.make CMakeFiles/AlphaLinkage.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaLinkage.dir/build.make CMakeFiles/AlphaLinkage.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaLinkage.dir/build.make CMakeFiles/AlphaLinkage.dir/main.cpp.s
.PHONY : main.cpp.s

utils/AlphaLinkage.o: utils/AlphaLinkage.cpp.o
.PHONY : utils/AlphaLinkage.o

# target to build an object file
utils/AlphaLinkage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DistanceLearning.dir/build.make CMakeFiles/DistanceLearning.dir/utils/AlphaLinkage.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaLinkage.dir/build.make CMakeFiles/AlphaLinkage.dir/utils/AlphaLinkage.cpp.o
.PHONY : utils/AlphaLinkage.cpp.o

utils/AlphaLinkage.i: utils/AlphaLinkage.cpp.i
.PHONY : utils/AlphaLinkage.i

# target to preprocess a source file
utils/AlphaLinkage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DistanceLearning.dir/build.make CMakeFiles/DistanceLearning.dir/utils/AlphaLinkage.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaLinkage.dir/build.make CMakeFiles/AlphaLinkage.dir/utils/AlphaLinkage.cpp.i
.PHONY : utils/AlphaLinkage.cpp.i

utils/AlphaLinkage.s: utils/AlphaLinkage.cpp.s
.PHONY : utils/AlphaLinkage.s

# target to generate assembly for a file
utils/AlphaLinkage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DistanceLearning.dir/build.make CMakeFiles/DistanceLearning.dir/utils/AlphaLinkage.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaLinkage.dir/build.make CMakeFiles/AlphaLinkage.dir/utils/AlphaLinkage.cpp.s
.PHONY : utils/AlphaLinkage.cpp.s

utils/CostFunction.o: utils/CostFunction.cpp.o
.PHONY : utils/CostFunction.o

# target to build an object file
utils/CostFunction.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DistanceLearning.dir/build.make CMakeFiles/DistanceLearning.dir/utils/CostFunction.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaLinkage.dir/build.make CMakeFiles/AlphaLinkage.dir/utils/CostFunction.cpp.o
.PHONY : utils/CostFunction.cpp.o

utils/CostFunction.i: utils/CostFunction.cpp.i
.PHONY : utils/CostFunction.i

# target to preprocess a source file
utils/CostFunction.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DistanceLearning.dir/build.make CMakeFiles/DistanceLearning.dir/utils/CostFunction.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaLinkage.dir/build.make CMakeFiles/AlphaLinkage.dir/utils/CostFunction.cpp.i
.PHONY : utils/CostFunction.cpp.i

utils/CostFunction.s: utils/CostFunction.cpp.s
.PHONY : utils/CostFunction.s

# target to generate assembly for a file
utils/CostFunction.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DistanceLearning.dir/build.make CMakeFiles/DistanceLearning.dir/utils/CostFunction.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaLinkage.dir/build.make CMakeFiles/AlphaLinkage.dir/utils/CostFunction.cpp.s
.PHONY : utils/CostFunction.cpp.s

utils/DistanceLearning.o: utils/DistanceLearning.cpp.o
.PHONY : utils/DistanceLearning.o

# target to build an object file
utils/DistanceLearning.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DistanceLearning.dir/build.make CMakeFiles/DistanceLearning.dir/utils/DistanceLearning.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaLinkage.dir/build.make CMakeFiles/AlphaLinkage.dir/utils/DistanceLearning.cpp.o
.PHONY : utils/DistanceLearning.cpp.o

utils/DistanceLearning.i: utils/DistanceLearning.cpp.i
.PHONY : utils/DistanceLearning.i

# target to preprocess a source file
utils/DistanceLearning.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DistanceLearning.dir/build.make CMakeFiles/DistanceLearning.dir/utils/DistanceLearning.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaLinkage.dir/build.make CMakeFiles/AlphaLinkage.dir/utils/DistanceLearning.cpp.i
.PHONY : utils/DistanceLearning.cpp.i

utils/DistanceLearning.s: utils/DistanceLearning.cpp.s
.PHONY : utils/DistanceLearning.s

# target to generate assembly for a file
utils/DistanceLearning.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DistanceLearning.dir/build.make CMakeFiles/DistanceLearning.dir/utils/DistanceLearning.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaLinkage.dir/build.make CMakeFiles/AlphaLinkage.dir/utils/DistanceLearning.cpp.s
.PHONY : utils/DistanceLearning.cpp.s

utils/Evaluation.o: utils/Evaluation.cpp.o
.PHONY : utils/Evaluation.o

# target to build an object file
utils/Evaluation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DistanceLearning.dir/build.make CMakeFiles/DistanceLearning.dir/utils/Evaluation.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaLinkage.dir/build.make CMakeFiles/AlphaLinkage.dir/utils/Evaluation.cpp.o
.PHONY : utils/Evaluation.cpp.o

utils/Evaluation.i: utils/Evaluation.cpp.i
.PHONY : utils/Evaluation.i

# target to preprocess a source file
utils/Evaluation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DistanceLearning.dir/build.make CMakeFiles/DistanceLearning.dir/utils/Evaluation.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaLinkage.dir/build.make CMakeFiles/AlphaLinkage.dir/utils/Evaluation.cpp.i
.PHONY : utils/Evaluation.cpp.i

utils/Evaluation.s: utils/Evaluation.cpp.s
.PHONY : utils/Evaluation.s

# target to generate assembly for a file
utils/Evaluation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DistanceLearning.dir/build.make CMakeFiles/DistanceLearning.dir/utils/Evaluation.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaLinkage.dir/build.make CMakeFiles/AlphaLinkage.dir/utils/Evaluation.cpp.s
.PHONY : utils/Evaluation.cpp.s

utils/Helpers.o: utils/Helpers.cpp.o
.PHONY : utils/Helpers.o

# target to build an object file
utils/Helpers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DistanceLearning.dir/build.make CMakeFiles/DistanceLearning.dir/utils/Helpers.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaLinkage.dir/build.make CMakeFiles/AlphaLinkage.dir/utils/Helpers.cpp.o
.PHONY : utils/Helpers.cpp.o

utils/Helpers.i: utils/Helpers.cpp.i
.PHONY : utils/Helpers.i

# target to preprocess a source file
utils/Helpers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DistanceLearning.dir/build.make CMakeFiles/DistanceLearning.dir/utils/Helpers.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaLinkage.dir/build.make CMakeFiles/AlphaLinkage.dir/utils/Helpers.cpp.i
.PHONY : utils/Helpers.cpp.i

utils/Helpers.s: utils/Helpers.cpp.s
.PHONY : utils/Helpers.s

# target to generate assembly for a file
utils/Helpers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DistanceLearning.dir/build.make CMakeFiles/DistanceLearning.dir/utils/Helpers.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaLinkage.dir/build.make CMakeFiles/AlphaLinkage.dir/utils/Helpers.cpp.s
.PHONY : utils/Helpers.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... AlphaLinkage"
	@echo "... DistanceLearning"
	@echo "... distance_main.o"
	@echo "... distance_main.i"
	@echo "... distance_main.s"
	@echo "... lib/AffineFunction.o"
	@echo "... lib/AffineFunction.i"
	@echo "... lib/AffineFunction.s"
	@echo "... lib/Clarkson.o"
	@echo "... lib/Clarkson.i"
	@echo "... lib/Clarkson.s"
	@echo "... lib/Hungarian.o"
	@echo "... lib/Hungarian.i"
	@echo "... lib/Hungarian.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... utils/AlphaLinkage.o"
	@echo "... utils/AlphaLinkage.i"
	@echo "... utils/AlphaLinkage.s"
	@echo "... utils/CostFunction.o"
	@echo "... utils/CostFunction.i"
	@echo "... utils/CostFunction.s"
	@echo "... utils/DistanceLearning.o"
	@echo "... utils/DistanceLearning.i"
	@echo "... utils/DistanceLearning.s"
	@echo "... utils/Evaluation.o"
	@echo "... utils/Evaluation.i"
	@echo "... utils/Evaluation.s"
	@echo "... utils/Helpers.o"
	@echo "... utils/Helpers.i"
	@echo "... utils/Helpers.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

